### ISSUE TITLE
Cannot open shared object file (Ubuntu 12.04LTS 32bit)

### ISSUE THREAD

**Issue by htdu87** [ttww/JavaFrameBuffer#1]
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /lib/libFrameBufferJNI.so: /lib/libFrameBufferJNI.so: cannot open shared object file: No such file or directory (Possible cause: can't load ARM-bit .so on a IA 32-bit platform)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at demoframebuffer.FrameBuffer.<clinit>(FrameBuffer.java:75)
    at demoframebuffer.TestFrameBuffer.<init>(TestFrameBuffer.java:35)
    at demoframebuffer.TestFrameBuffer$2.run(TestFrameBuffer.java:145)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by ttww** [comment]
You are using the Raspberry ARM binaries for the lib.
Compile it with the make file for x86 architecture.
